name: 'Close stale issues and PRs'
on:
  schedule:
    # 01:30 every day
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          stale-issue-message: 'This issue is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 5 days.'
          # turn off stale for both issues and PRs
          days-before-stale: -1
          # turn stale back on for issues only
          days-before-issue-stale: 30
          days-before-issue-close: 14
          exempt-issue-labels: 'pinned,security,enhancement,refactor,documentation,chore,bug,dependencies,needs-investigation'
