name: Unit tests for entrypoint

on:
  pull_request:
    branches:
      - '**'
    paths:
      - 'runner/**'
      - 'test/entrypoint/**'
      - '!**.md'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test entrypoint
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Run unit tests for entrypoint.sh
      run: |
        cd test/entrypoint
        bash entrypoint_unittest.sh
